Cargo.lock

No changes were needed, all passes (except the buggy ones) are passing

Update hvm-core verion

---

src/term/check/exhaustiveness.rs
src/term/check/type_check.rs
src/term/transform/encode_pattern_matching.rs
tests/golden_tests/compile_file/fst.hvm
tests/golden_tests/compile_file/fst_fst.hvm
tests/golden_tests/compile_file/match_tup.hvm
tests/snapshots/compile_file__fst.hvm.snap
tests/snapshots/compile_file__fst_fst.hvm.snap
tests/snapshots/compile_file__match_tup.hvm.snap

I'll open another pr to add the number pattern matching, I don't know how to do it yet

[sc-272] Add matching of pairs to pattern matching functions

---

Cargo.lock

See https://github.com/google/zerocopy/issues/716

Update deps to remove zerocopy unsoundness

---

src/term/check/unbound_vars.rs
src/term/parser/lexer.rs
src/term/parser/parser.rs
src/term/transform/encode_strs.rs
src/term/transform/flatten.rs
tests/golden_tests.rs
tests/snapshots/compile_file__bad_parens_making_erased_let.hvm.snap
tests/snapshots/compile_file__cyclic_dup.hvm.snap
tests/snapshots/compile_term__unbound_var.hvm.snap
tests/snapshots/compile_term__unbound_var_scope.hvm.snap

Run cargo fmt and clippy as well

Add def name to unbound var error msg

---

docs/writing-fusing-functions.md
examples/fusing_add.hvm

Clarify fusing functions documentation [sc-394] and add explanation on removing duplications

---

tests/golden_tests.rs
tests/snapshots/compile_file__addition_const.hvm.snap
tests/snapshots/compile_file__match_num_all_patterns.hvm.snap
tests/snapshots/compile_file__unused_dup_var_linearization.hvm.snap

We should really not merge prs directly without a rebase/merge and running the tests first.
When changing api of functions that are used in another pr at the same time, no conflict will be reported by github, but maybe we could have a CI to catch this things

Fix and update tests because of recent pr merges

---

src/lib.rs
src/main.rs
src/term/mod.rs
src/term/transform/definition_merge.rs
src/term/transform/mod.rs
src/term/transform/simplify_ref_to_ref.rs
tests/golden_tests.rs
tests/golden_tests/compile_file_o_all/merge_definitions.hvm
tests/golden_tests/encode_pattern_match/definition_merge.hvm
tests/golden_tests/encode_pattern_match/merge_recursive.hvm
tests/snapshots/compile_file_o_all__adt_option_and.hvm.snap
tests/snapshots/compile_file_o_all__ex0.hvm.snap
tests/snapshots/compile_file_o_all__list_merge_sort.hvm.snap
tests/snapshots/compile_file_o_all__merge_definitions.hvm.snap
tests/snapshots/compile_file_o_all__nested_adt_match.hvm.snap
tests/snapshots/compile_file_o_all__tagged_sup.hvm.snap
tests/snapshots/encode_pattern_match__and3.hvm.snap
tests/snapshots/encode_pattern_match__bool.hvm.snap
tests/snapshots/encode_pattern_match__definition_merge.hvm.snap
tests/snapshots/encode_pattern_match__flatten_era_pat.hvm.snap
tests/snapshots/encode_pattern_match__is_some_some.hvm.snap
tests/snapshots/encode_pattern_match__list_merge_sort.hvm.snap
tests/snapshots/encode_pattern_match__list_str_encoding_undeclared.hvm.snap
tests/snapshots/encode_pattern_match__match_adt_unscoped_var.hvm.snap
tests/snapshots/encode_pattern_match__merge_recursive.hvm.snap
tests/snapshots/encode_pattern_match__no_patterns.hvm.snap

Is this pass on the definitions satisfactory or would the pass on the INet/Net level be better?

[sc-306] merge identical functions

---

src/lib.rs
src/main.rs

Couldn't add a compile to rust option since those functions are not present in the hvmc lib

[sc-418] Improve hvml CLI options

---

Cargo.lock
Cargo.toml
src/net/hvmc_to_net.rs
src/net/net_to_hvmc.rs
src/term/builtins.rs
src/term/display.rs
src/term/mod.rs
src/term/net_to_term.rs
src/term/parser/parser.rs
src/term/term_to_net.rs
tests/golden_tests.rs

[sc-603] Update for new hvmc number/op type

---

src/fun/display.rs
src/fun/mod.rs
src/fun/parser.rs
src/fun/term_to_net.rs
src/fun/transform/desugar_do_blocks.rs
src/fun/transform/float_combinators.rs
src/imp/gen_map_get.rs
src/imp/mod.rs
src/imp/order_kwargs.rs
src/imp/parser.rs
src/imp/to_fun.rs
tests/golden_tests/compile_file/ask_outside_do.hvm
tests/golden_tests/parse_file/imp_program.hvm
tests/golden_tests/run_file/do_block_mixed.hvm
tests/snapshots/compile_file__ask_outside_do.hvm.snap
tests/snapshots/parse_file__imp_program.hvm.snap
tests/snapshots/run_file__do_block_mixed.hvm.snap

* complete 'do' in imp syntax
* make `,` optional in most places

[sc-681] Add monadic ask mixed with other terms

---

docs/syntax.md
src/imp/parser.rs

Also adds the missing quoted char parsing

[sc-700] Fix empty map parsing

---

Cargo.toml
LICENSE
LICENSE-APACHE

Added Apache 2.0 License, increased version and changed the description
New version - 0.2.7
New description - "A parallel language" <- Reverted

Add License to BEND

---

docs/native-numbers.md

Added some minor grammatical changes.

Minor grammatical mistakes in native-numbers.md

---

Cargo.lock
Cargo.toml
src/fun/parser.rs
src/imp/parser.rs
tests/golden_tests/compile_file/top_level_name_slashslash.bend
tests/snapshots/compile_file__top_level_name_slashslash.bend.snap

Dont allow top level names start with '//'

---

src/fun/parser.rs
tests/snapshots/compile_file__wrong_nums.bend.snap

throw an error on invalid numbers

---

src/lib.rs
src/main.rs
tests/golden_tests.rs

Continuing from #348 cause i want to merge it fast

Hvm path option

---

docs/native-numbers.md

Add <= and >= operators to the operation table in native-numbers.md to reflect the changes made in 0.2.34

Update operation table for 0.2.34

---

CHANGELOG.md

I found my hastily-written versioning scheme note to sound a bit funny, so I rephrased it. I also linked the unreleased section.

Update changelog a tiny bit

---

examples/list.bend

chore: update list.bend

---

src/imp/mod.rs
src/imp/parser.rs

Fix grammar description of a few statements

---

CHANGELOG.md
src/fun/transform/fix_match_terms.rs
tests/golden_tests.rs
tests/golden_tests/simplify_matches/irrefutable_case.bend
tests/snapshots/simplify_matches__irrefutable_case.bend.snap

Fix bugs with the irrefutable case optimization

---

docs/native-numbers.md

Fix a markdown in native numbers doc file

---

src/fun/transform/encode_adts.rs
src/imports/book.rs
tests/golden_tests/import_system/import_type.bend
tests/golden_tests/import_system/lib/MyOption.bend

Correctly apply the import rename to ADTs

---

docs/syntax.md

in order to match [HVM2.pdf](https://github.com/HigherOrderCO/HVM/blob/654276018084b8f44a22b562dd68ab18583bfb5b/paper/HVM2.pdf) section 6.6

update numbers and operations tables
