HigherOrderCO/Bend

- src/main.rs
❌ sintatically
✅ syntactically
> Fix typo (sintatically => syntactically)

- src/lib.rs
- src/main.rs
- src/term/display.rs
- src/term/mod.rs
- src/term/net_to_term.rs
- tests/golden_tests.rs
- tests/snapshots/encode_pattern_match__bool.hvm.snap
- tests/snapshots/encode_pattern_match__common.hvm.snap
- tests/snapshots/encode_pattern_match__expr.hvm.snap
- tests/snapshots/encode_pattern_match__list_merge_sort.hvm.snap
- tests/snapshots/encode_pattern_match__non_matching_fst_arg.hvm.snap
- tests/snapshots/flatten_rules__already_flat.hvm.snap
- tests/snapshots/flatten_rules__nested.hvm.snap
- tests/snapshots/flatten_rules__nested2.hvm.snap
- tests/snapshots/flatten_rules__nested_0ary.hvm.snap
- tests/snapshots/readback_lnet__bad_net.hvm.snap
- tests/snapshots/readback_lnet__nested_let.hvm.snap
- tests/snapshots/run_single_files__list_reverse.hvm.snap
- tests/snapshots/run_single_files__queue.hvm.snap
- tests/snapshots/run_single_files__tuple_rots.hvm.snap
(Based on #73 to avoid annoying merge conflicts.)
- combines the logic of `net_to_term_linear` and `net_to_term_non_linear`, as they were rather duplicative
- adds a cli flag to toggle between linear and non-linear readback
- improves the performance of readback by avoiding allocation of intermediate strings when printing
- prints chained applications without unnecessary parens (i.e. `(a b c)` instead of `((a b) c)`
- reworks the let insertion algorithm – now it always inserts at the lowest common ancestor of the uses of its variables, ignoring the free variables in `val`; this improves the readback of nested tuple destructures
> improve readback

- README.md
https://github.com/HigherOrderCO/hvm-core/pull/48 should probably be merged first, as the sup example with numeric operations is currently bugged on hvm-core
> [sc 308] Update readme with information about tagged terms

- src/term/transform/encode_pattern_matching.rs
- tests/golden_tests/encode_pattern_match/concat_def.hvm
- tests/snapshots/compile_file__fst_fst.hvm.snap
- tests/snapshots/encode_pattern_match__concat_def.hvm.snap
The desugar for String.concat was generating a wrong pattern definition:
```
(String.concat$P$P) = λy0 λx0 (String.concat$R0 x0 y0 x0 y0)
```
> Fix tuple defs applications

- src/term/transform/encode_pattern_matching.rs
- tests/golden_tests/compile_file/list_merge_sort.hvm
- tests/golden_tests/encode_pattern_match/pattern_match_encoding.hvm
- tests/snapshots/compile_file__and.hvm.snap
- tests/snapshots/compile_file__list_merge_sort.hvm.snap
- tests/snapshots/compile_file__scrutinee_reconstruction.hvm.snap
- tests/snapshots/encode_pattern_match__bool.hvm.snap
- tests/snapshots/encode_pattern_match__list_merge_sort.hvm.snap
- tests/snapshots/encode_pattern_match__nested_let_tup.hvm.snap
- tests/snapshots/encode_pattern_match__pattern_match_encoding.hvm.snap
This pr deals with the this part of the task:
Making the current program and compilation of:
```rs
data MyType = (A a) | (B b) | (C c) | (D d1 d2) | (E e1 e2)
Foo (A a) = R0
Foo * = R1
```
```rs
Foo = @x (x Foo$A Foo$B Foo$C Foo$D Foo$E)
Foo$R0 = @a R0
Foo$R1 = @* R1
Foo$A = @a (Foo$R0 a)
Foo$B = @b (Foo$R1 (B b))
Foo$C = @c (Foo$R1 (C c))
Foo$D = @d1 @d2 (Foo$R1 (D d1 d2))
Foo$E = @e1 @e2 (Foo$R1 (E e1 e2))
```
into this:
```rs
Foo = @x (x Foo$A Foo$B Foo$C Foo$D Foo$E)
Foo$R0 = @a R0
Foo$R1 = @* R1
Foo$A = @a (Foo$R0 *)
Foo$B = @b (Foo$R1 *)
Foo$C = @c (Foo$R1 *)
Foo$D = @d1 @d2 (Foo$R1 *)
Foo$E = @e1 @e2 (Foo$R1 *)
```
Instead of merging the now identical definitions of `Foo$B & Foo$C` and `Foo$D & Foo$E`, this can be done in a later pass to merge all identical definitions without …
> [sc-305] Simplify the generated encoding for pattern matching

- src/lib.rs
- src/term/transform/mod.rs
- src/term/transform/simplify_main_ref.rs
- src/term/transform/simplify_ref_to_ref.rs
- tests/golden_tests/compile_file/long_name.hvm
- tests/golden_tests/compile_file/repeated_name_trucation.hvm
- tests/golden_tests/run_file/repeated_name_trucation.hvm
- tests/snapshots/compile_file__eta.hvm.snap
- tests/snapshots/compile_file__linearize_match.hvm.snap
- tests/snapshots/compile_file__list_merge_sort.hvm.snap
- tests/snapshots/compile_file__long_name.hvm.snap
- tests/snapshots/compile_file__match_mult_linearization.hvm.snap
- tests/snapshots/compile_file__nested_eta.hvm.snap
- tests/snapshots/compile_file__repeated_name_trucation.hvm.snap
- tests/snapshots/run_file__repeated_name_trucation.hvm.snap
This pr implements the first option described in the task:
1. One would be to have main be a duplicate of the function it's referencing. This is the simplest option.
2. Another option would be to have the other function be merged with main, replacing all calls to it with calls to main.
> [sc-311] fix ref to ref removal pass

- docs/automatic-vectorization-with-tagged-lambdas.md
It used the old tagged lambda syntax. I updated it to prevent users from getting confused.
> [sc-360] Update hvm-lang tagged lambda documentation

- src/lib.rs
- src/term/check/exhaustiveness.rs
- src/term/check/type_check.rs
- src/term/display.rs
- src/term/mod.rs
- src/term/transform/desugar_match_expressions.rs
- tests/golden_tests.rs
- tests/snapshots/encode_pattern_match__var_only.hvm.snap
This will be used for the next PR where I'll finally fix unscoped vars in adt matches
> [sc-332] Separate adt match extraction from num match normalization

- docs/builtin-defs.md
- docs/compiler-options.md
- src/lib.rs
- tests/golden_tests/run_file/print.hvm
Add `HVM.print`, which prints a string using its `Display` representation into stdout, and then outputs a newline. I also fixed a typo in the docs.
> Add `HVM.print`

- src/diagnostics.rs
- src/term/check/shared_names.rs
- src/term/mod.rs
- src/term/transform/resolve_refs.rs
- tests/golden_tests/compile_file/error_messages.hvm
- tests/snapshots/compile_file__error_messages.hvm.snap
Because `join` method does not insert a newline at the end
> [sc-485] Error printing not correctly breaking lines

- src/diagnostics.rs
- src/lib.rs
- src/term/check/mod.rs
- src/term/check/repeated_bind.rs
- src/term/transform/definition_pruning.rs
- tests/golden_tests/compile_file/repeated_bind_match.hvm
- tests/golden_tests/compile_file/repeated_bind_rule.hvm
- tests/snapshots/cli__compile_pre_reduce.hvm.snap
- tests/snapshots/compile_file__crlf.hvm.snap
- tests/snapshots/compile_file__match_num_all_patterns.hvm.snap
- tests/snapshots/compile_file__match_num_unscoped_lambda.hvm.snap
- tests/snapshots/compile_file__repeated_bind_match.hvm.snap
- tests/snapshots/compile_file__repeated_bind_rule.hvm.snap
This depends on #221, leaving as a draft until that is merged
> [sc 492] Re-add repeated bind in match-arm/rule patterns warning

- src/term/transform/linearize_matches.rs
- tests/golden_tests/simplify_matches/complex_with_case.hvm
- tests/snapshots/simplify_matches__complex_with_case.hvm.snap
Was linearizing incorrectly when a `let` or `use` depended on a lambda variable that is not used by the match, but not linearized because it comes before a lambda variable that IS used by the match.
> [sc-654] Fix linearize binds before match

- README.md
HVM2 has been renamed HVM and HVM has been renamed HVM1. Fixed 2 places in the README.md to fix that.
> Fix hvm1 and hvm2 links to accomodate repo renames

- README.md
Updates the URL of PAPER.pdf from
https://github.com/HigherOrderCO/HVM/raw/main/PAPER.pdf
to
https://github.com/HigherOrderCO/HVM/raw/main/paper/PAPER.pdf
> Update paper URL

- src/main.rs
Hi, I did this because I needed it for personal use. Since the "bend check [file]" command returned 0 in $?, even if it failed or reported an error. So in order to being able to check the exit status of "bend check" I added a return ExitCode::FAILURE, when execute_cli_mode(cli) returned a diagnostics message to main().
> Changed return type of fn main() in src/main.rs to fn main() -> std::process::ExitCode.

- GUIDE.md
In **GUIDE.md**, the definition of `List` is given but it is missing the recursive `~` marker on the `tail`.
This PR adds it where it should be.
> Add missing recursive marker in List definition.

- GUIDE.md
As briefly discussed on Discord, the Guide states that the type of strings is `List`, when it is in fact `String`. A note has been added to clarify that they are in fact distinct types with the same implementation.
> Update Guide to elaborate on the type of String.

- FEATURES.md
- GUIDE.md
- README.md
- docs/syntax.md
Improve description clarity, remove trailing spaces.
I honestly don't understand the purpose of `x-2` in the last case of a switch. In all the examples I tried, the name was bound to the conditional - 2, which doesn't match how I understood the description.
> Documentation edits

- README.md
The sum example's run commands currently run the sum program in a sequential fashion in all cases. Correcting the run command's target allows the example to actually demonstrate parallel processing.
> Run correct file in sum example

- CHANGELOG.md
Clean up the changelog format to obey the dictates of the [KeepAChangelog spec](https://keepachangelog.com/en/1.1.0/).
I think that this should be relatively uncontroversial, but I did have a few thoughts.
I didn't add in an "unreleased" section, as I wasn't sure if y'all want to get into the habit of writing changelogs alongside changes. If so, I can add it in.
Secondly, the changelog header now says that this follows SemVer. While SemVer pre-1.0 says that you can do anything you want breaking-changes-wise, it does imply that you intend in following SemVer post-1.0. Is that accurate?
Thirdly, there aren't tags for many recent releases. I linked them anyway, figuring that they could be backfilled.
Even if you decide not to conform to KeepAChangelog, I'd still recommend linking releases …
> Standardize Changelog Format

- GUIDE.md
- tests/golden_tests/run_file/guide_shader_dummy.bend
Necessary due to the newly-implemented safety checking for HVM.
Fixes #576
> Change shader example in the guide

- CHANGELOG.md
- README.md
- src/main.rs
- tests/snapshots/cli__debug_list_map.bend.snap
- tests/snapshots/cli__debug_u60_to_nat.bend.snap
> #620 Changed `bend run` to `bend run-rs` and `bend run` defaults to the C implementation

- CHANGELOG.md
- docs/syntax.md
- src/imp/parser.rs
- tests/golden_tests/parse_file/tuple_assign.bend
- tests/golden_tests/parse_file/tuple_commas.bend
- tests/golden_tests/parse_file/tuple_need_parens.bend
- tests/snapshots/parse_file__tuple_assign.bend.snap
- tests/snapshots/parse_file__tuple_commas.bend.snap
- tests/snapshots/parse_file__tuple_need_parens.bend.snap
Tuples without parentheses are now freely accepted in assignments, returns and lambdas, in other cases we must use `(..., ...)`
> #554 tuples should be defined by commas like python not by parentheses

- examples/list.bend
Adds funcions equals and tail. The first compares two Lists and returns 1 if they're equal, and 0 otherwise. The second returns the tail of a given list.
> Add List equals and tail to the list.bend example

- docs/dups-and-sups.md
I know this is kind of low-hanging fruit with no real impact, but was very annoying, hence the PR.
> Fix grammar in dups-and-sups.md

- GUIDE.md
- docs/syntax.md
> Update guide and add comment in syntax doc

- src/fun/transform/resugar_list.rs
- src/fun/transform/resugar_string.rs
#713 
* Create  struct to wrap user-provided cons handling functions, implementing the  trait.
* Implement  struct to handle default cons patterns, also implementing the  trait.
* Replace  with  type, better expressing success or failure semantics.
* Utilize Rust's pattern matching and  method to simplify error handling process.
> Refactor Transform String Resugar Term Scott 

- src/fun/builtins.bend
- tests/golden_tests/io/utf8.bend
- tests/snapshots/io__utf8.bend.snap
Previously calling `(String/decode_utf8 [])` would return `"\0"`.  This PR makes it return `""`, adds this case to `utf8.bend` and updates the snapshot.
Fixes #701
> Fix `String/decode_utf8` returning a non-empty string when given an empty list

- docs/builtins.md
- src/fun/builtins.bend
- tests/golden_tests.rs
- tests/golden_tests/compile_file_o_all/match_adt_non_exhaustive.bend
- tests/golden_tests/encode_pattern_match/match_adt_unscoped_lambda.bend
- tests/golden_tests/encode_pattern_match/match_adt_unscoped_var.bend
- tests/golden_tests/prelude/applies_function_to_map.bend
- tests/golden_tests/prelude/get_values_from_map.bend
- tests/golden_tests/prelude/lists_to_map.bend
- tests/golden_tests/prelude/map_checked_test.bend
- tests/golden_tests/prelude/map_contains_test.bend
- tests/golden_tests/prelude/set_node_when_empty.bend
- tests/golden_tests/run_file/unbound_wrap.bend
- tests/golden_tests/simplify_matches/double_unwrap_maybe.bend
- tests/snapshots/compile_file_o_all__match_adt_non_exhaustive.bend.snap
- tests/snapshots/desugar_file__mapper_syntax.bend.snap
- tests/snapshots/encode_pattern_match__full_map.bend.snap
- tests/snapshots/encode_pattern_match__match_adt_unscoped_lambda.bend.snap
- tests/snapshots/encode_pattern_match__match_adt_unscoped_var.bend.snap
- tests/snapshots/parse_file__imp_map.bend.snap
- tests/snapshots/parse_file__imp_program.bend.snap
- tests/snapshots/prelude__applies_function_to_map.bend.snap
- tests/snapshots/prelude__get_values_from_map.bend.snap
- tests/snapshots/prelude__lists_to_map.bend.snap
- tests/snapshots/prelude__map_checked_test.bend.snap
- tests/snapshots/prelude__map_contains_test.bend.snap
- tests/snapshots/prelude__set_node_when_empty.bend.snap
- tests/snapshots/run_file__unbound_wrap.bend.snap
- tests/snapshots/simplify_matches__double_unwrap_maybe.bend.snap
The following updates have been made to `builtins.bend`:
- **New type definition:**
```bend
type Maybe(T):
Some {val: T}
None
```
- **Updated type definition:**
```bend
type Map(T):
Node {value: Maybe(T), ~left: Map(T), ~right: Map(T)}
Leaf
```
Now, every `Node` stores a `Maybe` type to explicitly represent the presence or absence of a value.
```
- **Updated/added functions:**
- `Maybe/unwrap`: Retrieves the value inside Maybe/Some
- `Map/set`: Inserts or updates a value in the map.
- `Map/get`: Retrieves a value from the map, returning a `Maybe` type.
- `Map/map`: Applies a function to each value in the map.
- `Map/contains`: Checks whether a key exists in the map.
- `Map/get_check`: Retrieves a value and performs additional validation.
---
- You cannot see which elements are in the Map, …
```
> Updates builtin type Map so that it stores Maybes in its nodes.
